# Generated by Django 3.0.6 on 2020-07-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('accessed', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('path', models.CharField(max_length=200)),
                ('tags', models.ManyToManyField(to='core.Tag')),
            ],
        ),
    ]
